### ISSUE TITLE
This Newbie does not understand how to implement this!

### ISSUE THREAD

**Issue by M1GDevin** [VerityIncorporated/LethalOS#1]
Hello! As stated in the title I'm still new when making Custom mod packs let alone mods. Still, I'm not completely clueless and want to understand A: Why does the example menu not show up in-game anywhere (when first looking at all the options and explicitly typing out Example, Example Module, etc) and not being able to find the examples and B: If examples are not immediately working in the mod where do I "code" (copy and paste with edits) in my custom menu modules?

Edit: I also now see you have linked to Bepinex v6.0.0 which is not the current version that the thunderstore uses (Thats v5.4.21) but went out of my way and tried it out by itself and with Bepinex (both versions) also with LCAPI and the examples including LethalOS which I also did try and still nothing so if you could make your documentation more clear for newbies like me and make sure you use the right version of bepinex that would be very apricated!

**Comment by CallMeVerity** [comment]
Thanks for letting me know that Thunderstore uses version 5.4.21 of BepInEx, I was not aware of this and I will update that shortly. I am not sure I understand the problem you're having, the example works just fine for me. Are you available on discord perhaps?

**Comment by CallMeVerity** [comment]
I've re-coded the entire project to use the correct version of BepInEx.

It is now a separate dependency, and I will add easier to understand documentation.
