### ISSUE TITLE
Missing references & incompatibility

### ISSUE THREAD

**Issue by ZuckerSchock** [VerityIncorporated/LethalOS#2]
Project came without any references for me, had to guess/search which ones could have been used and add references manually, found everything except one reference, which i am still searching right now: 

The type or namespace name 'Mono' does not exist in the namespace 'BepInEx.Unity' (are you missing an assembly reference?)	
"using BepInEx.Unity.Mono;"
"LethalOS\Loader.cs"	2	Active

**Comment by ZuckerSchock** [comment]
Ah i have an idea, i had issues with your BepInEx version.
So i installed BepInEx 6.0.0-pre.1 which worked for me, but it could be, that "BepInEx.Unity" in v6.0 does not include Mono or something like that.

**Comment by ZuckerSchock** [comment]
Yep i was right, BepInEx Mono 6.0 pre.1 includes only "BepInEx.Unity" your version includes "BepInEx.Unity.Mono".

Guess i got it now.
Its not easy to set up under these conditions.

**Comment by ZuckerSchock** [comment]
Seems to be working as intended for me now. But others will most likely have similar issues.

**Comment by ZuckerSchock** [comment]
Your BepInEx version does work for me as well, but its incompatible with basically all other mods available, even ones for BepInEx6.

**Comment by CallMeVerity** [comment]
I've updated the mod so that its easier to implement, its now a separate Dependency and is using the correct BepInEx version, DLL's are automatically resolved in the DLL folder, you can replace them with update DLL's from your own game if required.
